image: maven:3.5.0-jdk-8

variables:
  MAVEN_CLI_OPTS: "-s .mvn/settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.mvn/repository -DaltDeploymentRepository=responsum::default::${ARTIFACTORY_URL}"
cache:
  paths:
  - .mvn/repo/
  - target/


build-snapshot:
  image: maven:3.5.0-jdk-8
  stage: build
  tags:
  - latest
  script:
  - mvn -U $MAVEN_CLI_OPTS -DskipTests=true -U install --batch-mode
  only:
  - develop